# Generated by Django 3.1.3 on 2020-11-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('longName', models.CharField(default='', max_length=255)),
                ('symbol', models.CharField(default='', max_length=255)),
                ('sector', models.CharField(default='', max_length=255)),
                ('profitMargins', models.CharField(default='', max_length=255)),
                ('stocks', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
